apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infitek-erp-ingress
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: infitek.test.huaqing.run
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infitek-web
                port:
                  number: 80
