apiVersion: v1
kind: Secret
metadata:
  name: infitek-erp-secret
  namespace: test
type: Opaque
stringData:
  DB_PASS: "<replace-with-your-db-password>"
  JWT_SECRET: "<replace-with-your-jwt-secret>"
