import { MigrationInterface, QueryRunner, Table, TableForeignKey, TableIndex } from 'typeorm';

export class CreateSalesOrdersTable20260426000100 implements MigrationInterface {
  name = 'CreateSalesOrdersTable20260426000100';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'sales_orders',
        columns: [
          { name: 'id', type: 'bigint', unsigned: true, isPrimary: true, isGenerated: true, generationStrategy: 'increment' },
          { name: 'erp_sales_order_code', type: 'varchar', length: '32' },
          { name: 'domestic_trade_type', type: 'varchar', length: '20' },
          { name: 'external_order_code', type: 'varchar', length: '100' },
          { name: 'order_type', type: 'varchar', length: '30' },
          { name: 'customer_id', type: 'bigint', unsigned: true },
          { name: 'customer_name', type: 'varchar', length: '200' },
          { name: 'customer_code', type: 'varchar', length: '50' },
          { name: 'customer_contact_person', type: 'varchar', length: '100', isNullable: true },
          { name: 'after_sales_source_order_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'after_sales_source_order_code', type: 'varchar', length: '32', isNullable: true },
          { name: 'after_sales_product_summary', type: 'text', isNullable: true },
          { name: 'destination_country_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'destination_country_name', type: 'varchar', length: '100', isNullable: true },
          { name: 'payment_term', type: 'varchar', length: '80', isNullable: true },
          { name: 'shipment_origin_country_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'shipment_origin_country_name', type: 'varchar', length: '100', isNullable: true },
          { name: 'signing_company_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'signing_company_name', type: 'varchar', length: '200', isNullable: true },
          { name: 'salesperson_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'salesperson_name', type: 'varchar', length: '100', isNullable: true },
          { name: 'other_industry_note', type: 'varchar', length: '255', isNullable: true },
          { name: 'currency_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'currency_code', type: 'varchar', length: '20', isNullable: true },
          { name: 'currency_name', type: 'varchar', length: '50', isNullable: true },
          { name: 'currency_symbol', type: 'varchar', length: '20', isNullable: true },
          { name: 'trade_term', type: 'varchar', length: '10', isNullable: true },
          { name: 'destination_port_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'destination_port_name', type: 'varchar', length: '200', isNullable: true },
          { name: 'bank_account', type: 'varchar', length: '255', isNullable: true },
          { name: 'extra_viewer_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'extra_viewer_name', type: 'varchar', length: '100', isNullable: true },
          { name: 'primary_industry', type: 'varchar', length: '50', isNullable: true },
          { name: 'exchange_rate', type: 'decimal', precision: 18, scale: 6, isNullable: true },
          { name: 'transportation_method', type: 'varchar', length: '30', isNullable: true },
          { name: 'crm_signed_at', type: 'date', isNullable: true },
          { name: 'contract_amount', type: 'decimal', precision: 18, scale: 2, default: 0 },
          { name: 'order_nature', type: 'varchar', length: '40', isNullable: true },
          { name: 'secondary_industry', type: 'varchar', length: '50', isNullable: true },
          { name: 'receipt_status', type: 'varchar', length: '30', isNullable: true },
          { name: 'status', type: 'varchar', length: '30' },
          { name: 'contract_file_keys', type: 'json', isNullable: true },
          { name: 'contract_file_names', type: 'json', isNullable: true },
          { name: 'received_amount', type: 'decimal', precision: 18, scale: 2, default: 0 },
          { name: 'merchandiser_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'merchandiser_name', type: 'varchar', length: '100', isNullable: true },
          { name: 'merchandiser_abbr', type: 'varchar', length: '20', isNullable: true },
          { name: 'outstanding_amount', type: 'decimal', precision: 18, scale: 2, default: 0 },
          { name: 'required_delivery_at', type: 'date', isNullable: true },
          { name: 'is_shared_order', type: 'varchar', length: '10', isNullable: true },
          { name: 'is_sinosure', type: 'varchar', length: '10', isNullable: true },
          { name: 'is_palletized', type: 'varchar', length: '10', isNullable: true },
          { name: 'requires_customs_certificate', type: 'varchar', length: '10', isNullable: true },
          { name: 'is_split_in_advance', type: 'varchar', length: '10', isNullable: true },
          { name: 'uses_marketing_fund', type: 'varchar', length: '10', isNullable: true },
          { name: 'requires_export_customs', type: 'varchar', length: '10', isNullable: true },
          { name: 'requires_warranty_card', type: 'varchar', length: '10', isNullable: true },
          { name: 'requires_maternity_handover', type: 'varchar', length: '10', isNullable: true },
          { name: 'customs_declaration_method', type: 'varchar', length: '30', isNullable: true },
          { name: 'plug_photo_keys', type: 'json', isNullable: true },
          { name: 'is_insured', type: 'varchar', length: '10', isNullable: true },
          { name: 'is_ali_trade_assurance', type: 'varchar', length: '10', isNullable: true },
          { name: 'ali_trade_assurance_order_code', type: 'varchar', length: '100', isNullable: true },
          { name: 'forwarder_quote_note', type: 'text', isNullable: true },
          { name: 'consignee_company', type: 'text', isNullable: true },
          { name: 'consignee_other_info', type: 'text', isNullable: true },
          { name: 'notify_company', type: 'text', isNullable: true },
          { name: 'notify_other_info', type: 'text', isNullable: true },
          { name: 'shipper_company', type: 'text', isNullable: true },
          { name: 'shipper_other_info_company_id', type: 'bigint', unsigned: true, isNullable: true },
          { name: 'shipper_other_info_company_name', type: 'varchar', length: '200', isNullable: true },
          { name: 'domestic_customer_company', type: 'text', isNullable: true },
          { name: 'domestic_customer_delivery_info', type: 'text', isNullable: true },
          { name: 'uses_default_shipping_mark', type: 'varchar', length: '10', isNullable: true },
          { name: 'shipping_mark_note', type: 'varchar', length: '255', isNullable: true },
          { name: 'shipping_mark_template_key', type: 'varchar', length: '255', isNullable: true },
          { name: 'needs_invoice', type: 'varchar', length: '10', isNullable: true },
          { name: 'invoice_type', type: 'varchar', length: '30', isNullable: true },
          { name: 'shipping_documents_note', type: 'varchar', length: '500', isNullable: true },
          { name: 'bl_type', type: 'varchar', length: '30', isNullable: true },
          { name: 'original_mail_address', type: 'text', isNullable: true },
          { name: 'business_rectification_note', type: 'text', isNullable: true },
          { name: 'customs_document_note', type: 'text', isNullable: true },
          { name: 'other_requirement_note', type: 'text', isNullable: true },
          { name: 'product_total_amount', type: 'decimal', precision: 18, scale: 2, default: 0 },
          { name: 'expense_total_amount', type: 'decimal', precision: 18, scale: 2, default: 0 },
          { name: 'total_amount', type: 'decimal', precision: 18, scale: 2, default: 0 },
          { name: 'created_at', type: 'datetime', default: 'CURRENT_TIMESTAMP' },
          { name: 'updated_at', type: 'datetime', default: 'CURRENT_TIMESTAMP', onUpdate: 'CURRENT_TIMESTAMP' },
          { name: 'created_by', type: 'varchar', length: '100', isNullable: true },
          { name: 'updated_by', type: 'varchar', length: '100', isNullable: true },
        ],
      }),
    );

    await queryRunner.createIndices('sales_orders', [
      new TableIndex({ name: 'idx_sales_orders_customer_id', columnNames: ['customer_id'] }),
      new TableIndex({ name: 'idx_sales_orders_status', columnNames: ['status'] }),
      new TableIndex({ name: 'idx_sales_orders_order_type', columnNames: ['order_type'] }),
      new TableIndex({ name: 'idx_sales_orders_created_at', columnNames: ['created_at'] }),
    ]);

    await queryRunner.createForeignKeys('sales_orders', [
      new TableForeignKey({
        columnNames: ['customer_id'],
        referencedTableName: 'customers',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['destination_country_id'],
        referencedTableName: 'countries',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['shipment_origin_country_id'],
        referencedTableName: 'countries',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['signing_company_id'],
        referencedTableName: 'companies',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['currency_id'],
        referencedTableName: 'currencies',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['destination_port_id'],
        referencedTableName: 'ports',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['salesperson_id'],
        referencedTableName: 'users',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['extra_viewer_id'],
        referencedTableName: 'users',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['merchandiser_id'],
        referencedTableName: 'users',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['shipper_other_info_company_id'],
        referencedTableName: 'companies',
        referencedColumnNames: ['id'],
      }),
      new TableForeignKey({
        columnNames: ['after_sales_source_order_id'],
        referencedTableName: 'sales_orders',
        referencedColumnNames: ['id'],
      }),
    ]);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('sales_orders');
  }
}
